---
# Set up vagrant for docker

- name: install docker
  yum: name=docker-io state=latest
  become: yes

- name: ensure docker group
  group: name=docker state=present
  become: yes

- name: add current user to docker group
  user: name=vagrant groups=docker append=yes
  become: yes

- name: start docker
  service: name=docker state=started
  become: yes
