---
# Install rdopkg

- name: enable rdopkg repo
  get_url: url=https://copr.fedoraproject.org/coprs/jruzicka/rdopkg/repo/epel-7/jruzicka-rdopkg-epel-7.repo dest=/etc/yum.repos.d/jruzicka-rdopkg-epel-7.repo
  become: yes

- name: install rdopkg
  yum: name=rdopkg state=latest
  become: yes
