---
- hosts: all

  roles:
    - centos
    - dev

  tasks:
    - name: install yum-plugin-priorities
      yum: name=yum-plugin-priorities state=latest
      become: yes

    - name: enable delorean deps repo
      get_url: url=http://trunk.rdoproject.org/centos7/delorean-deps.repo dest=/etc/yum.repos.d/delorean-deps.repo
      become: yes

    - name: enable current delorean repo
      get_url: url=http://trunk.rdoproject.org/centos7/current-passed-ci/delorean.repo dest=/etc/yum.repos.d/delorean.repo
      become: yes

    # uncomment below if you want to try out the very latest repo that have not passed CI yet
    #- name: enable bleeding edge delorean repo
    #  get_url: url=http://trunk.rdoproject.org/centos7/current/delorean.repo dest=/etc/yum.repos.d/delorean.repo
    #  become: yes

    - name: install packstack
      yum: name=openstack-packstack state=latest
      become: yes

    # packstack would ask for root password to install the ssh key if not already
    - authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      become: yes

    - name: packstack aio
      command: packstack --allinone
      # non-interactive environment does not include sbin
      # TODO: investigate why centos does it for us
      environment:
        PATH: /usr/bin:/bin:/usr/sbin:/sbin
