---
- hosts: all

  roles:
    - centos
    - dev
    - docker
    - python-dev
    - rdopkg

  tasks:
    - name: install dependencies needed for delorean
      yum: name=createrepo,selinux-policy state=latest
      become: yes

    - name: install packages needed for delorean virtualenv dependencies
      yum: name=gcc state=latest
      become: yes

    - name: fetch delorean
      git: repo=https://github.com/openstack-packages/delorean.git dest=~/delorean

    - name: fix selinux context for delorean scripts
      shell: chcon -t docker_exec_t ~/delorean/scripts/*

    - name: build base docker image for delorean
      command: su -l vagrant ./delorean/scripts/create_build_image.sh
      become: yes

    - name: install delorean venv
      shell: virtualenv delorean-venv && . delorean-venv/bin/activate && cd delorean && python setup.py develop

    - name: set .bashrc to enter virtualenv on login
      lineinfile: dest=~/.bashrc line="{{ item.line }}" insertafter=EOF create=True
      with_items:
        - { line: "alias delorean='delorean --config-file projects.ini --local --dev --package-name'" }
        - { line: 'cd delorean' }
        - { line: '. ../delorean-venv/bin/activate' }
