---
# Install misc development tools

- name: install misc development tools
  yum: name=git,tig,vim,tmux,git-review,python-bugzilla,ctags,bash-completion state=latest
  become: yes

- name: initialize custom configuration files
  git: repo=https://github.com/booxter/configs.git dest=/home/homedir
  become: yes
  notify:
    - install homedir
